// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAH2utZxuBNTs1Uk4f_5CRPLCx3nPZb_o',
    appId: '1:819161511250:web:a09ec30ffdd007fb52f68b',
    messagingSenderId: '819161511250',
    projectId: 'ayurvedaapp-91230',
    authDomain: 'ayurvedaapp-91230.firebaseapp.com',
    storageBucket: 'ayurvedaapp-91230.firebasestorage.app',
    measurementId: 'G-6G8H58Z84X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmQeMos5BOE6-gTnuSSJkd0ZSWaLsUNpo',
    appId: '1:819161511250:android:2ed325a090a5194652f68b',
    messagingSenderId: '819161511250',
    projectId: 'ayurvedaapp-91230',
    storageBucket: 'ayurvedaapp-91230.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjWzsNPgphWqLUmJiLr6EDx-4YrWLQvTU',
    appId: '1:819161511250:ios:2fe99e28a30d4d3c52f68b',
    messagingSenderId: '819161511250',
    projectId: 'ayurvedaapp-91230',
    storageBucket: 'ayurvedaapp-91230.firebasestorage.app',
    iosBundleId: 'com.example.ayurvedaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjWzsNPgphWqLUmJiLr6EDx-4YrWLQvTU',
    appId: '1:819161511250:ios:2fe99e28a30d4d3c52f68b',
    messagingSenderId: '819161511250',
    projectId: 'ayurvedaapp-91230',
    storageBucket: 'ayurvedaapp-91230.firebasestorage.app',
    iosBundleId: 'com.example.ayurvedaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAH2utZxuBNTs1Uk4f_5CRPLCx3nPZb_o',
    appId: '1:819161511250:web:546d056a0cc36c6f52f68b',
    messagingSenderId: '819161511250',
    projectId: 'ayurvedaapp-91230',
    authDomain: 'ayurvedaapp-91230.firebaseapp.com',
    storageBucket: 'ayurvedaapp-91230.firebasestorage.app',
    measurementId: 'G-68ELSW5RPF',
  );
}
